Initial implementation of swagger documentation.
SSE-GROUP5/wakeup-system pull request #19
Opened 2024-01-29 15:59 UTC by Kang2001

2024-01-29 18:22 UTC, davidfrisch requested changes
As talked in WhatsApp, the swagger has to be included in the main flask server.

2024-02-01 00:39 UTC, davidfrisch requested changes
Please remove the .idea from the commit

2024-02-01 00:41 UTC, davidfrisch requested changes
Is it possible to reduce this file and move the titles and functino that combines into another file ? You should create a folder docs and put the json files in it.

2024-02-01 00:49 UTC, Kang2001 commented
> Is it possible to reduce this file and move the titles and functino that combines into another file ? You should move it in the swagger docs

yes, I will change it.

2024-02-01 19:01 UTC, Kang2001 commented
> Thanks Weihao, looks better and better.
> 
> However, the endpoints are not correct. 
> 
> Please find attached the latest endpoints.
> 
> [WakeUpServer.postman_collection.json](https://github.com/SSE-GROUP5/wakeup-system/files/14129484/WakeUpServer.postman_collection.json)
> 
> 

Thank you David, I will check it again.

2024-02-01 19:01 UTC, Kang2001 commented on swagger-doc/wakeup-server/Json/switch_api.json
> +  "host": "localhost:5000",
Yes, I will change it.

2024-03-07 10:15 UTC, davidfrisch approved these changes

2024-03-07 10:15 UTC, merged